### ISSUE TITLE
Error during V11+e installation

### ISSUE THREAD

**Issue by AntoineFouille** [BADEP/addons#5]
Hello,
I tried to set up the module for odoo v11 (entreprise edition). I got the following traceback 
`

Error while importing module 'crm_facebook_leads': "Impossible de charger le module crm_facebook_leads échec : fichier /tmp/tmpq06ez9x4/crm_facebook_leads/security/ir.model.access.csv :\nAucun enregistrement trouvé pour id externe 'model_crm_facebook_page' dans le champ 'Object'\nMissing required value for the field 'Object' (model_id)\nAucun enregistrement trouvé pour id externe 'model_crm_facebook_form' dans le champ 'Object'\nMissing required value for the field 'Object' (model_id)\nAucun enregistrement trouvé pour id externe 'model_crm_facebook_page' dans le champ 'Object'\nMissing required value for the field 'Object' (model_id)\nAucun enregistrement trouvé pour id externe 'model_crm_facebook_form' dans le champ 'Object'\nMissing required value for the field 'Object' (model_id)\nAucun enregistrement trouvé pour id externe 'model_crm_facebook_form_field' dans le champ 'Object'\nMissing required value for the field 'Object' (model_id)"
--

`

Here the video of procedure : https://drive.google.com/open?id=17CAHfn8c-JHeShVOgiQD88HlNmG2tbbp

**Comment by metamasterplay** [comment]
Hello,

As far as I know base_import_module only works for importing modules without any python code. You should instead copy the module folder directly in one of folder present in the addon path. Usulally it's <path_to_odoo_user_home>/.local/share/Odoo/addons/11.0
